### PR TITLE
Plotting updates

### PR DESCRIPTION
**Pull request by JanvanderLinden**
Adding plotting functions:

### unrolled plot

Can be called as a `cf.PlotVariables1D` task with
```
--plot-function columnflow.plotting.cmsGhent.unrolled.plot_unrolled
```
and two dimensional variables, e.g
```
--variables bjet_HT-anc_4j4b__n_btagL
```
or a three dimensional variables, e.g.
```
--variables n_jet-anc_4j4b__n_btagM-n_genjet
```
where the first variable is the one displayed on the x axis and the second one is the ancillary binning.
`x_labels` and `discrete_x=True` of the ancillary variable can be used to put labels on each of the side-by-side plots.
The tag "Ancillary region X:" is currently pre-pended per default.

For 3d variables, the third variable is the gen level variable for splitting the processes.
Per default all processes are merged along the third axis, unless they are specified in the general options:
```
--general-settings split_processes=ttbb+ttcc
```
The labels of the split processes are updated based on the `x_labels` of the gen level observable.

Example 2d:

image

Example 3d:

image

### Other changes

Additionally some modifications have been made for the migration matrix plotting, to force both axes to be of equal binning.
This allows also to plot migration matrices, and the purities and efficiencies, when e.g. the reco-level binning is more fine-grained than the gen-level bins. 

Results in something like this:

image

(note that first and last bin edges are not forced to be equal)

### Bug fixes

Passing 1D variable groups worked fine, but when passing groups of 2D or 3D variables to the command line this failed to parse the variables correctly. This has been fixed with some small modifications to the parsing algorithm.

### CODE REVIEW

**Comment by maadcoen** [comment]
what's up with the colours in the migration plot?

**Comment by JanvanderLinden** [comment]
> what's up with the colours in the migration plot?

the binning on the x axis is finer than on the y axis, so the colors reflect the individual binnings while the numbers and the grid reflect the uniform binning

**Comment by maadcoen** [comment]
> > what's up with the colours in the migration plot?
> 
> the binning on the x axis is finer than on the y axis, so the colors reflect the individual binnings while the numbers and the grid reflect the uniform binning

you think that's useful to have the old binning still represented? Looks confusing to me, and not very neat. Also, peculiar that going by the color 70% of the genlevel bin 2-4 seems to end up in the reco bin 2-~2.5. Is this just the data here, or is there something fishy?

**Comment by JanvanderLinden** [comment]
> > > what's up with the colours in the migration plot?
> > 
> > 
> > the binning on the x axis is finer than on the y axis, so the colors reflect the individual binnings while the numbers and the grid reflect the uniform binning
> 
> you think that's useful to have the old binning still represented? Looks confusing to me, and not very neat. Also, peculiar that going by the color 70% of the genlevel bin 2-4 seems to end up in the reco bin 2-~2.5. Is this just the data here, or is there something fishy?

its the steeply falling spectrum that overpopulates the 2.-2.5 bin compared to 2.5-4. looks fine to me.
I think its good to have as an option to have the finer binning still represented, it reflects more closely the two distributions of relevance - reco with reco binning and gen with gen binning. I could add a command line option to  (de)activate it

**Comment by maadcoen** [comment]
> > > > what's up with the colours in the migration plot?
> > > 
> > > 
> > > the binning on the x axis is finer than on the y axis, so the colors reflect the individual binnings while the numbers and the grid reflect the uniform binning
> > 
> > 
> > you think that's useful to have the old binning still represented? Looks confusing to me, and not very neat. Also, peculiar that going by the color 70% of the genlevel bin 2-4 seems to end up in the reco bin 2-~2.5. Is this just the data here, or is there something fishy?
> 
> its the steeply falling spectrum that overpopulates the 2.-2.5 bin compared to 2.5-4. looks fine to me. I think its good to have as an option to have the finer binning still represented, it reflects more closely the two distributions of relevance - reco with reco binning and gen with gen binning. I could add a command line option to (de)activate it

Adding the option seems like a good idea. I would make the colours match the numbers by default, and add the option to activate the finer binning.

**Comment by maadcoen** [comment]
made the changes to migration plot, also merged the 2d and 3d variants into one plotting function, which behaves differently depending on whether a 2d or 3d variable is provided

**Review by maadcoen — APPROVED** [review]

**Pull request merged**
