### PR TITLE
Update config___cf_short_name_lc__.py

### PR DESCRIPTION
**Pull request by maadcoen**
Luminosity 2018 error called 2017

### CODE REVIEW

**Comment by maadcoen** [comment]
also added uncertainties that I think should be used when you analyse a year on its own

**Comment by datikavt** [comment]
Seems like a typo. Do you know if the uncertainty matches? 
Would be cool if you can link here where you found the single year uncertainties also.

**Comment by maadcoen** [comment]
I just asked the Joscha, and using the normal uncertainties should add up to the standalone versions, so it's not necessary to use the standalone uncertainty. I'll remove them again. Here is [the link](https://twiki.cern.ch/twiki/bin/view/CMS/LumiRecommendationsRun2#2018) btw.

**Comment by datikavt** [comment]
Ok, cool thanks! So this is the uncorrelated 2018.

**Review by datikavt — APPROVED** [review]

**Pull request merged**
